#!/bin/bash

echo "Post Push"
printenv

shortVersion=${SOURCE_BRANCH%.*-php*}
phpVersion=${SOURCE_BRANCH#*-}
tag="${shortVersion}-${phpVersion}"

docker tag $IMAGE_NAME $DOCKER_REPO:${tag}
docker push $DOCKER_REPO:${tag}
